-- Employees Table
CREATE TABLE EMPLOYEES (
    EMP_ID NUMBER PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) CHECK(EMAIL LIKE '%@%')
);

-- Projects Table
CREATE TABLE PROJECTS (
    PROJECT_ID NUMBER(10) PRIMARY KEY,
    PROJECT_NAME VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

-- Tasks Table
CREATE TABLE TASKS (
    TASK_ID NUMBER(20) PRIMARY KEY,
    PROJECT_ID NUMBER(20),
    TASK_NAME VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);

-- Allocations Table
CREATE TABLE ALLOCATIONS (
    APPLICATION_ID NUMBER PRIMARY KEY,
    EMP_ID NUMBER(20),
    TASK_ID NUMBER(20),
    ALLOCATION_DATE DATE NOT NULL,
    HOURS_ALLOCATION NUMBER,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    FOREIGN KEY (TASK_ID) REFERENCES TASKS(TASK_ID)
);
