-- Total hours worked by each employee
SELECT e.NAME, SUM(a.HOURS_ALLOCATION) AS TOTAL_HOURS
FROM EMPLOYEES e
JOIN ALLOCATIONS a ON e.EMP_ID = a.EMP_ID
GROUP BY e.NAME;

-- Employees working on each project
SELECT p.PROJECT_NAME, e.NAME, t.TASK_NAME
FROM PROJECTS p
JOIN TASKS t ON p.PROJECT_ID = t.PROJECT_ID
JOIN ALLOCATIONS a ON t.TASK_ID = a.TASK_ID
JOIN EMPLOYEES e ON a.EMP_ID = e.EMP_ID;
